# -*- coding: utf-8 -*-
"""Explosophore-Based Molecular Library Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnw2WyXmtRN_r84-7GIXKTM3ngfEC9D2

# **Explosophore-Based Molecular Library Generator**
"""

# -*- coding: utf-8 -*-
"""
Explosophore-Based Molecular Library Generator v2.0
=====================================================
Generates large libraries of energetic molecules by substituting
explosophore groups onto a user-supplied scaffold SMILES.

Architecture: fragment-based substitution (no RDKit reaction SMARTS),
modelled after the reliable cast/template approach in molecule_generator.py

Key fixes vs v1:
  - No SMARTS string-slicing bugs
  - No atom-index corruption after RemoveAtom
  - Works with RDKit implicit H model (no need for explicit H atoms)
  - Monte Carlo complexity filter (same as molecule_generator.py)
  - Clean CSV output, no Colab dependencies
"""

import csv
import random
import warnings
import time
import os
import numpy as np
from tqdm import tqdm
from rdkit import Chem
from rdkit.Chem import AllChem, rdMolDescriptors
from rdkit.Chem import RWMol

warnings.filterwarnings("ignore")

# ─────────────────────────────────────────────
# 1.  EXPLOSOPHORE FRAGMENT LIBRARY
#     Each entry is a complete SMILES fragment.
#     The attachment point is marked with [*] or [1*].
#     We use Chem.ReplaceSubstructs to graft them.
# ─────────────────────────────────────────────

EXPLOSOPHORE_FRAGMENTS = {
    # name              : (attachment_smiles,               category)
    "NO2"               : ("[N+](=O)[O-]",                  "nitro"),
    "ONO2"              : ("O[N+](=O)[O-]",                 "nitrate_ester"),
    "NNO2"              : ("N[N+](=O)[O-]",                 "nitramine"),
    "C(NO2)3"           : ("C([N+](=O)[O-])([N+](=O)[O-])[N+](=O)[O-]",  "trinitromethyl"),
    "C(NO2)2F"          : ("C([N+](=O)[O-])([N+](=O)[O-])F","dinitrofluoromethyl"),
    "C(NO2)2NF2"        : ("C([N+](=O)[O-])([N+](=O)[O-])N(F)F", "dinitrodifluoroaminomethyl"),
    "C(NO2)2N3"         : ("C([N+](=O)[O-])([N+](=O)[O-])N=[N+]=[N-]", "dinitroa zidomethyl"),
    "NF2"               : ("N(F)F",                         "difluoroamine"),
    "N3"                : ("N=[N+]=[N-]",                   "azide"),
    "OClO3"             : ("OCl(=O)(=O)=O",                 "perchlorate_ester"),
    "NClO3"             : ("NCl(=O)(=O)=O",                 "perchlorate_amine"),
    "N(O)=NNO2"         : ("[N+]([O-])=N[N+](=O)[O-]",     "diazeniumdinitro"),
    "F"                 : ("F",                             "fluorine"),          # simple baseline
    "Cl"                : ("Cl",                            "chlorine"),
    "CN"                : ("CN",                            "methylamine"),       # low-energy baseline
    "CH3"               : ("C",                             "methyl"),
    "CF3"               : ("C(F)(F)F",                      "trifluoromethyl"),
    "NH2"               : ("N",                             "amine"),
    "OH"                : ("O",                             "hydroxyl"),
    "NHNO2"             : ("N[N+](=O)[O-]",                 "nitramine"),
}

# ─────────────────────────────────────────────
# 2.  HELPER: attach one fragment to one site
# ─────────────────────────────────────────────

def attach_fragment(mol: Chem.Mol, atom_idx: int, frag_smiles: str) -> Chem.Mol | None:
    """
    Replace one implicit H on atom_idx with frag_smiles.
    Returns a new sanitized Mol or None on failure.

    Strategy (avoids RDKit reaction SMARTS entirely):
      1. Convert the target atom's implicit H to an explicit [H] neighbour.
      2. Build the fragment mol.
      3. Use Chem.CombineMols + EditableMol to form a new bond.
      4. Remove the [H] atom.
      5. Sanitize and return.
    """
    try:
        # ── step 1: add one explicit H to the site ──
        rw = RWMol(Chem.AddHs(mol))  # all implicit → explicit
        # find an H neighbour of atom_idx
        h_idx = None
        for nbr in rw.GetAtomWithIdx(atom_idx).GetNeighbors():
            if nbr.GetAtomicNum() == 1:
                h_idx = nbr.GetIdx()
                break
        if h_idx is None:
            return None  # no H available at this site

        # ── step 2: build fragment ──
        frag = Chem.MolFromSmiles(frag_smiles)
        if frag is None:
            return None

        # ── step 3: find the attachment atom in the fragment ──
        # We define attachment as atom index 0 of the fragment SMILES
        frag = Chem.AddHs(frag)
        attach_atom_in_frag = 0  # always atom 0 of the fragment

        # ── step 4: combine and bond ──
        combo = Chem.CombineMols(rw.GetMol(), frag)
        edit = RWMol(combo)
        n_rw = rw.GetNumAtoms()
        # bond: site_atom ← → attach_atom_in_frag (offset by n_rw)
        edit.AddBond(atom_idx, n_rw + attach_atom_in_frag, Chem.BondType.SINGLE)
        # remove the H we are replacing
        edit.RemoveAtom(h_idx)

        product = edit.GetMol()
        # remove remaining explicit H for clean SMILES
        product = Chem.RemoveHs(product)
        Chem.SanitizeMol(product)
        return product

    except Exception:
        return None


# ─────────────────────────────────────────────
# 3.  COMPLEXITY SCORING  (same logic as molecule_generator.py)
# ─────────────────────────────────────────────

def complexity_score(n_substitutions: int) -> int:
    """Simple proxy: each non-H substitution adds 1 to complexity score."""
    return n_substitutions


def accept_complexity(cs: int, x0: int, max_cs: int, beta: float) -> bool:
    """Monte Carlo acceptance of a complexity score."""
    if cs <= x0:
        return True
    if cs > max_cs:
        return False
    dx = (cs - x0) / (max_cs - x0)
    return random.random() < np.exp(-beta * dx)


# ─────────────────────────────────────────────
# 4.  MAIN GENERATOR CLASS
# ─────────────────────────────────────────────

class ExplosophoreGenerator:
    """
    Generate a library of energetic molecules by substituting
    explosophore fragments onto a scaffold.

    Parameters
    ----------
    scaffold_smiles : str
        SMILES of the core scaffold (e.g. "c1cnccn1").
    n_molecules     : int
        Target library size.
    max_subs        : int
        Maximum number of substitution sites per molecule.
    complexity_max  : int
        Maximum complexity score (CS) allowed.
    x0              : int
        CS below which all molecules are accepted.
    beta            : float
        Boltzmann-like penalisation factor (higher = stricter).
    fragment_weights: dict | None
        Optional {fragment_name: weight} dict. Uniform if None.
    output_csv      : str
        Path for output CSV file.
    """

    def __init__(
        self,
        scaffold_smiles: str,
        n_molecules: int = 5000,
        max_subs: int = 3,
        complexity_max: int = 8,
        x0: int = 3,
        beta: float = 4.0,
        fragment_weights: dict | None = None,
        output_csv: str = "energetic_library.csv",
    ):
        mol = Chem.MolFromSmiles(scaffold_smiles)
        if mol is None:
            raise ValueError(f"Invalid scaffold SMILES: {scaffold_smiles!r}")
        Chem.SanitizeMol(mol)
        self.scaffold = mol
        self.scaffold_smiles = scaffold_smiles

        self.n_molecules = n_molecules
        self.max_subs = max_subs
        self.complexity_max = complexity_max
        self.x0 = x0
        self.beta = beta
        self.output_csv = output_csv

        # substitutable sites = heavy atoms that carry at least one implicit H
        self.sites = [
            a.GetIdx()
            for a in self.scaffold.GetAtoms()
            if a.GetTotalNumHs() > 0
        ]
        if not self.sites:
            raise ValueError(
                "Scaffold has no substitutable (H-bearing) sites. "
                "Check your SMILES or use a scaffold with free H positions."
            )

        # fragment pool
        self.frag_names = list(EXPLOSOPHORE_FRAGMENTS.keys())
        if fragment_weights:
            w = [fragment_weights.get(n, 1.0) for n in self.frag_names]
        else:
            w = [1.0] * len(self.frag_names)
        total = sum(w)
        self.frag_weights = [x / total for x in w]

        print(f"✅ Scaffold loaded: {scaffold_smiles}")
        print(f"   Substitutable sites : {len(self.sites)}")
        print(f"   Fragment pool size  : {len(self.frag_names)}")
        print(f"   Target library size : {n_molecules}\n")

    # ── generate one candidate molecule ──
    def _generate_one(self):
        k = random.randint(1, min(self.max_subs, len(self.sites)))
        chosen_sites = random.sample(self.sites, k)
        chosen_frags = random.choices(self.frag_names, weights=self.frag_weights, k=k)

        current = self.scaffold
        cs = 0
        for site, frag_name in zip(chosen_sites, chosen_frags):
            frag_smiles, _ = EXPLOSOPHORE_FRAGMENTS[frag_name]
            result = attach_fragment(current, site, frag_smiles)
            if result is None:
                return None, 0, []
            current = result
            cs += 1  # each successful substitution +1 CS

        smiles = Chem.MolToSmiles(current, canonical=True)
        return smiles, cs, chosen_frags

    # ── generate the full library ──
    def generate(self) -> list[dict]:
        generated = []
        seen = set()
        attempts = skipped = duplicates = 0
        max_attempts = self.n_molecules * 500  # generous ceiling

        pbar = tqdm(total=self.n_molecules, desc="Generating library")

        with open(self.output_csv, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(
                f, fieldnames=["Number", "SMILES", "Complexity", "Num_Subs", "Groups"]
            )
            writer.writeheader()

            while len(generated) < self.n_molecules and attempts < max_attempts:
                attempts += 1

                smiles, cs, frags = self._generate_one()

                if smiles is None:
                    skipped += 1
                    continue
                if smiles in seen:
                    duplicates += 1
                    continue
                if not accept_complexity(cs, self.x0, self.complexity_max, self.beta):
                    continue

                row = {
                    "Number"    : len(generated) + 1,
                    "SMILES"    : smiles,
                    "Complexity": cs,
                    "Num_Subs"  : len(frags),
                    "Groups"    : ";".join(frags),
                }
                writer.writerow(row)
                generated.append(row)
                seen.add(smiles)
                pbar.update(1)

        pbar.close()

        print(f"\n✅ Library complete!")
        print(f"   Molecules generated : {len(generated)}")
        print(f"   Failed attachments  : {skipped}")
        print(f"   Duplicates skipped  : {duplicates}")
        print(f"   Total attempts      : {attempts}")
        print(f"   Output saved to     : {self.output_csv}\n")
        return generated


# ─────────────────────────────────────────────
# 5.  ENTRY POINT
# ─────────────────────────────────────────────

def main():
    print("=" * 55)
    print("  Explosophore-Based Molecular Library Generator v2.0")
    print("=" * 55)

    scaffold = input("\nScaffold SMILES (e.g. C1=NC=NC=N1): ").strip()
    n_mol    = int(input("How many molecules? [5000]: ").strip() or 5000)
    max_subs = int(input("Max substituents per molecule? [3]: ").strip() or 3)
    beta     = float(input("Beta (complexity strictness, higher=stricter) [4]: ").strip() or 4)
    out_csv  = input("Output CSV filename [energetic_library.csv]: ").strip() or "energetic_library.csv"

    t0 = time.time()
    gen = ExplosophoreGenerator(
        scaffold_smiles=scaffold,
        n_molecules=n_mol,
        max_subs=max_subs,
        complexity_max=8,
        x0=3,
        beta=beta,
        output_csv=out_csv,
    )
    gen.generate()
    print(f"⏱  Done in {time.time() - t0:.1f} s")


if __name__ == "__main__":
    main()